### ISSUE TITLE
ATIS / UR Voice Service question

### ISSUE THREAD

**Issue by 132nd-Entropy** [etcher-be/esst#1]
follow up from the other repository. 

hello, I had to reinstall and re-setup ESST on the 132nd server and it works nicely, but it doesnt look like the ATIS is running. Are there any instructions on how to set this up, Ive been looking in the readme.rst but could not find anything.

 @132nd-Entropy 132nd-Entropy added the question  label a day ago
@etcher-be
 Contributor
etcher-be commented 7 hours ago
There's no documentation yet unfortunately.

Try adding the following to your config file:

atis:
  create: 'true'
For ESST development and support in the future, I will be monitoring this repository instead: https://github.com/etcher-be/esst

**Comment by 132nd-Entropy** [comment]
I have:

atis:
create: 'true'

in the config file and the ESST-side of the ATIS seems to work. 
(I can type !atis show UGKO and ESST will output the METAR)

However, I am unsure as of how to get the ATIS that ESST generated into the UR Voice Server. I have UR voice server running and minimized as per instructions on the UR website, its displaying:  

Radio requests received: 0

**Comment by etcher-be** [comment]
In order to be able to investigate, I will need the log from esst.

In the mean time, could you make sure that teamspeak is running and that the UR plugin is active when trying to listen in on the ATIS?

Also, please note that the ATIS feature is currently limited to the Caucasus map, and will not function correctly in any other theatre.

**Comment by 132nd-Entropy** [comment]
thanks for the help, its appreciated. After rebooting the server now ESST will exit with a bunch of error messages

**Comment by 132nd-Entropy** [comment]
which I was able to solve by setting atis create false in the config now esst is startiung up again. I try rerunning it with the atis enabled

**Comment by etcher-be** [comment]
The link to the log file isn't working for me, sadly.

The runtime error with the ATIS comes from the following METAR string: 

`UGTB 241428Z 16602MPS CAVOK FEW164 21.200000762939/21.200000762939 Q1016 NOSIG`

I believe the temperature part is the issue. The decoding of METARs is done by https://github.com/etcher-be/emiz, I will look into it.

**Comment by 132nd-Entropy** [comment]
https://www.dropbox.com/s/kys9cm3ufplzged/ESST.log?raw=1


here is a link to the log

**Comment by 132nd-Entropy** [comment]
if I run ESST with ATIS generate on, it will exit before I can do anything. 
If I set  ATIS generate false and load a mission, I get this: 

BOTMr. Slave: 16:33:54
Unable to parse METAR: XXXX 241433Z 16603MPS CAVOK FEW164 23.200000762939/23.200000762939 Q1015 NOSIG

then I can load the mission by saying -i UGKO and it will load (yet no ATIS)

**Comment by etcher-be** [comment]
From the log, I can tell the METAR string is the issue.

This is the relevant part: 
```
C:\Users\132nd\AppData\Local\Temp\tmp0glccpf9EMFT_
2018-06-24 16:28:29,829     INFO ESST.esst.atis._atis_generator 2364 MainProcess 5732 <concurrent.futures.thread.ThreadPoolExecutor object at 0x0000025420E47438>_0 c:\users\132nd\miniconda3\envs\esst\lib\site-packages\esst\atis\_atis_generator.py[87].generate_atis: creating ATIS from METAR: XXXX 241428Z 16602MPS CAVOK FEW164 21.200000762939/21.200000762939 Q1016 NOSIG
2018-06-24 16:28:29,829    DEBUG ESST.esst.atis._atis_generator 2364 MainProcess 5732 <concurrent.futures.thread.ThreadPoolExecutor object at 0x0000025420E47438>_0 c:\users\132nd\miniconda3\envs\esst\lib\site-packages\esst\atis\_atis_generator.py[88].generate_atis: parsing METAR string
2018-06-24 16:28:29,830    DEBUG EMIZ 2364 MainProcess 5732 <concurrent.futures.thread.ThreadPoolExecutor object at 0x0000025420E47438>_0 c:\users\132nd\miniconda3\envs\esst\lib\site-packages\emiz\weather\custom_metar\custom_metar.py[43].get_metar: building CustomMetar from: UGTB 241428Z 16602MPS CAVOK FEW164 21.200000762939/21.200000762939 Q1016 NOSIG
2018-06-24 16:28:29,830    DEBUG EMIZ 2364 MainProcess 5732 <concurrent.futures.thread.ThreadPoolExecutor object at 0x0000025420E47438>_0 c:\users\132nd\miniconda3\envs\esst\lib\site-packages\emiz\weather\custom_metar\custom_metar.py[22].__init__: creating METAR from: UGTB 241428Z 16602MPS CAVOK FEW164 21.200000762939/21.200000762939 Q1016 NOSIG
2018-06-24 16:28:29,830    ERROR ESST.esst.atis._atis_generator 2364 MainProcess 5732 <concurrent.futures.thread.ThreadPoolExecutor object at 0x0000025420E47438>_0 c:\users\132nd\miniconda3\envs\esst\lib\site-packages\esst\atis\_atis_generator.py[93].generate_atis: failed to parse METAR
```

That issue comes from EMIZ and is something that's been fixed in a recent commit.

What I can also see in the log is that ESST is running out of a Miniconda installation; it is most likely that the version you're running is outdated; assuming it is the case, the version of EMIZ installed does not have the latest fixes, which makes it really hard for me to resolve the issue.

In order to install the latest version of ESST, please use `pipenv` from a 64bits 3.6 Python installation:

```CMD
pipenv install esst
pipenv run esst
```

Assuming nothing has changed since the last time I was on TeamViewer, 3.6 should be the default Python installation, and the latest `esst_startup.bat` file should have all the steps needed to run the latest version of ESST.

**Comment by 132nd-Entropy** [comment]
I think that did it thanks for the help. Reason why it was running out of Miniconda was because I tried to set it up (after it not working) according to the instructions in the readme of the repo (which apparently is very outdated). 

here is our startup bat file (when the server reboots its stuck at 'installing ESST' but if I close that window and manually restart the bat file it seems to work 

`@echo off
pipenv install esst
pipenv update esst
call activate ESST
cd C:\Utils\ESST
pipenv run esst
pause`

**Comment by 132nd-Entropy** [comment]
thanks that new batchfile did the job! It did a bunch of updates. No joy on the voice server, but I think this is an UR issue probably more than a ESST issue. When I manually load the UR voice server and input either the soundfile that ESST generates, or a text metar and click 'add service' nothing happens

**Comment by 132nd-Entropy** [comment]
ok today after server restart, I still get the errors that apparently there is no config file present. I run the batfile attached here

https://www.dropbox.com/s/ioxrhm2537rx5vt/run_esst.bat?raw=1

this is the log
https://www.dropbox.com/s/z4eitmlm4mdzdv2/ESST.log?raw=1

and here is the config
https://www.dropbox.com/s/z4eitmlm4mdzdv2/ESST.log?raw=1

they all reside in c/Utils/ESST

any idea what Im doing wrong?
